<!DOCTYPE HTML>
<html lang="en">

<!-- Mirrored from www.autohotkey.com/docs/v1/lib/Try.htm by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 04 Sep 2024 09:25:18 GMT -->
<head>
<title>Try - Syntax &amp; Usage | AutoHotkey v1</title>
<meta name="description" content="The Try statement guards one or more statements against runtime errors and exceptions thrown by the Throw statement." />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link href="../static/theme.css" rel="stylesheet" type="text/css" />
<script src="../static/content.js" type="text/javascript"></script>
</head>
<body>

<h1>Try <span class="ver">[v1.1.04+]</span></h1>

<p>Guards one or more <a href="../Concepts.html#statement">statements</a> against runtime errors and exceptions thrown by the <a href="Throw.html">Throw</a> statement.</p>

<pre class="Syntax"><span class="func">Try</span> <i>Statement</i></pre>
<pre class="Syntax" style="line-height: 100%">
<span class="func">Try</span>
{
    <i>Statements</i>
}
</pre>
<h2 id="Remarks">Remarks</h2>
<p>The <em>Try</em> statement is usually followed by a <a href="Block.html">block</a> (one or more <a href="../Concepts.html#statement">statements</a> enclosed in braces). If only a single statement is to be executed, it can be placed on the same line as <em>Try</em> or on the next line, and the braces can be omitted. To specify code that executes only when <em>Try</em> catches an error, use the <a href="Catch.html">Catch</a> statement.</p>
<p>An exception can be thrown by the <a href="Throw.html">Throw</a> statement or by the program when a runtime error occurs. When an exception is thrown from within a <em>Try</em> block or a function called by one, the following occurs:</p>
<ul>
  <li>If there is a corresponding <a href="Catch.html">Catch</a> statement, execution continues there.</li>
  <li>If there is no <em>Catch</em> statement but there is a <a href="Finally.html">Finally</a> statement, it is executed, but once it finishes the exception is automatically thrown again.</li>
  <li>If there is neither a <em>Catch</em> statement nor a <em>Finally</em> statement, execution continues at the next line outside the <em>Try</em> block.</li>
</ul>
<p>If an exception is thrown while no <em>Try</em> blocks are executing, an error message is shown and the current thread exits.</p>
<p>The <a href="Block.html#otb">One True Brace (OTB) style</a> may optionally be used with <em>Try</em>. For example:</p>
<pre>try {
    ...
} catch e {
    ...
}</pre>

<h2 id="Related">Related</h2>
<p><a href="Catch.html">Catch</a>, <a href="Throw.html">Throw</a>, <a href="Finally.html">Finally</a>, <a href="Block.html">Blocks</a>, <a href="OnError.html">OnError()</a></p>

<h2 id="Examples">Examples</h2>
<div class="ex" id="ex_basic">
<p><a class="ex_number" href="#ex_basic"></a> Demonstrates the basic concept of <em>Try-Catch</em> and <em>Throw</em>.</p>
<pre>try  <em>; Attempts to execute code.</em>
{
    HelloWorld()
    MakeToast()
}
<a href="Catch.html">catch</a> e  <em>; Handles the first error/exception raised by the block above.</em>
{
    MsgBox, An exception was thrown!`nSpecifically: %e%
    <a href="Exit.html">Exit</a>
}

HelloWorld()  <em>; Always succeeds.</em>
{
    MsgBox, Hello, world!
}

MakeToast()  <em>; Always fails.</em>
{
    <em>; Jump immediately to the try block's error handler:</em>
    <a href="Throw.html">throw</a> A_ThisFunc " is not implemented, sorry"
}
</pre>
</div>

<div class="ex" id="ex_el">
<p><a class="ex_number" href="#ex_el"></a> Demonstrates the use of <em>Try-Catch</em> instead of <a href="../misc/ErrorLevel.html">ErrorLevel</a>.</p>
<pre>try
{
    <em>; The following tries to back up certain types of files:</em>
    FileCopy, %A_MyDocuments%\*.txt, D:\Backup\Text documents
    FileCopy, %A_MyDocuments%\*.doc, D:\Backup\Text documents
    FileCopy, %A_MyDocuments%\*.jpg, D:\Backup\Photos
}
catch
{
    MsgBox, 16,, There was a problem while backing the files up!
    ExitApp
}
</pre>
</div>

<div class="ex" id="ex_com">
<p><a class="ex_number" href="#ex_com"></a> Demonstrates the use of <em>Try-Catch</em> dealing with COM errors. For details about the COM object used below, see <a href="https://learn.microsoft.com/previous-versions/visualstudio/visual-studio-6.0/aa227633(v=vs.60)">Using the ScriptControl (Microsoft Docs)</a>.</p>
<pre>try
{
    obj := <a href="ComObjCreate.html">ComObjCreate</a>("ScriptControl")
    obj.ExecuteStatement("MsgBox ""This is embedded VBScript""")
    obj.InvalidMethod() <em>; This line produces a runtime error.</em>
}
catch e
{
    <em>; For more detail about the object that e contains, see <a href="Throw.html#Exception">Exception()</a>.</em>
    MsgBox, 16,, % "Exception thrown!`n`nwhat: " e.what "`nfile: " e.file
        . "`nline: " e.line "`nmessage: " e.message "`nextra: " e.extra
}
</pre>
</div>

<div class="ex" id="ex_nesting">
<p><a class="ex_number" href="#ex_nesting"></a> Demonstrates nesting <em>Try-Catch</em> statements.</p>
<pre>try Example1() <em>; Any single statement can be on the same line with Try.</em>
catch e
    MsgBox, Example1() threw %e%.

Example1()
{
    try Example2()
    catch e
    {
        if (e = 1)
            throw e <em>; Rethrow the exception so that the caller can catch it.</em>
        else
            MsgBox, Example2() threw %e%.
    }
}

Example2()
{
    Random, o, 1, 2
    throw o
}</pre>
</div>

<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" data-cf-beacon='{"rayId":"8bdcedfc1f191911","version":"2024.8.0","r":1,"serverTiming":{"name":{"cfL4":true}},"token":"5204006f3e8e418e97b0c729c9eb0334","b":1}' crossorigin="anonymous"></script>
</body>

<!-- Mirrored from www.autohotkey.com/docs/v1/lib/Try.htm by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 04 Sep 2024 09:25:18 GMT -->
</html>
